### ISSUE TITLE
White lines at the tabs wrapper + upper and down browser window

### ISSUE THREAD

**Issue by NullGates** [Ashley-Cause/GlassFox#1]
Greetings,

First, thank you for your work on this project. After trying numerous transparency configurations, yours is the only one that has worked for me! :)
I encountered a small visual issue related to the sidebar, which I was able to resolve with a custom CSS modification. Specifically, there were three persistent white lines (highlighted in red rectangles in the image below):

![Firefox troubleshooting](https://github.com/user-attachments/assets/bd97938d-1ea0-4053-bf4a-71e2fc1a868a)

After some investigation, I managed to remove these lines by adding the following code to my `UserChrome.css` file:
```
.wrapper {
    border-inline-end: 0 !important;
  }

:root {
  --chrome-content-separator-color: transparent !important;
  --tabs-navbar-separator-color: transparent !important;
  --tabs-navbar-separator-style: transparent !important;
}
```

This fix worked for my setup and may help others encountering the same issue.

Environment:
- Operating System: MacOS Sonoma 14.6.1
- Firefox Version: 130.0 (64-bit)
- System Integrity Protection (SIP): Enabled

Hopefully, this solution can save someone else some time. Please feel free to reach out if any further clarification is needed.

Thank you again for your work!

**Comment by Ashley-Cause** [comment]
Hey there, 
I've encountered that problem before too, but couldn't figure out a way to resolve it, so thanks for your help.

On the other hand, since creating the original `userChrome.css` file, I've found a far better way to implement this transparency, and have not noticed any problems with borders on my setup.

If you feel like updating your `userChrome.css` file, I'd be grateful if you could let me know if this new implementation fixes the bug for you anyway.

Thanks for your help!

**Comment by NullGates** [comment]
I updated to the new `userChrome.css` which indeed fixed the bug and also made the top navbar look cleaner ! Thank you :)
